- project:
    templates:
      - tempest-plugin-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - sahara-buildimages-spark:
            voting: false
